"""initial_schema

Revision ID: 001
Revises:
Create Date: 2026-01-05

Initial database schema with all tables and correct foreign key relationships.
"""

#  Copyright (C) 2010-2026 Evolveum and contributors
#
#  Licensed under the EUPL-1.2 or later.

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("idx_sessions_created_at", "sessions", ["created_at"], unique=False)
    op.create_index("idx_sessions_updated_at", "sessions", ["updated_at"], unique=False)
    op.create_table(
        "documentation_items",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for the documentation chunk",
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("source IN ('scraper', 'upload')", name="check_doc_source"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_doc_items_created_at", "documentation_items", ["created_at"], unique=False)
    op.create_index(
        "idx_doc_items_metadata_gin", "documentation_items", ["metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_doc_items_page_id", "documentation_items", ["page_id"], unique=False)
    op.create_index("idx_doc_items_session_id", "documentation_items", ["session_id"], unique=False)
    op.create_index("idx_doc_items_source", "documentation_items", ["source"], unique=False)
    op.create_index(op.f("ix_documentation_items_created_at"), "documentation_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_documentation_items_page_id"), "documentation_items", ["page_id"], unique=False)
    op.create_index(op.f("ix_documentation_items_session_id"), "documentation_items", ["session_id"], unique=False)
    op.create_index(op.f("ix_documentation_items_source"), "documentation_items", ["source"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("errors", sa.ARRAY(sa.Text()), nullable=True),
        sa.CheckConstraint("status IN ('queued', 'running', 'finished', 'failed')", name="check_job_status"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index("idx_jobs_session_id", "jobs", ["session_id"], unique=False)
    op.create_index("idx_jobs_status", "jobs", ["status"], unique=False)
    op.create_index("idx_jobs_status_type_created", "jobs", ["status", "job_type", "created_at"], unique=False)
    op.create_index("idx_jobs_type", "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_session_id"), "jobs", ["session_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "session_data",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "key", name="uq_session_data_session_key"),
    )
    op.create_index("idx_session_data_key", "session_data", ["key"], unique=False)
    op.create_index("idx_session_data_session_id", "session_data", ["session_id"], unique=False)
    op.create_index(op.f("ix_session_data_key"), "session_data", ["key"], unique=False)
    op.create_index(op.f("ix_session_data_session_id"), "session_data", ["session_id"], unique=False)
    op.create_table(
        "job_progress",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("total_processing", sa.Integer(), nullable=True),
        sa.Column("processing_completed", sa.Integer(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_progress_job_id"), "job_progress", ["job_id"], unique=True)
    op.create_table(
        "relevant_chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documentation_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "entity_type", "doc_id", name="uq_relevant_chunk_unique"),
    )
    op.create_index("idx_relevant_chunks_doc_id", "relevant_chunks", ["doc_id"], unique=False)
    op.create_index("idx_relevant_chunks_entity_type", "relevant_chunks", ["entity_type"], unique=False)
    op.create_index("idx_relevant_chunks_session_id", "relevant_chunks", ["session_id"], unique=False)
    op.create_index(
        "idx_relevant_chunks_session_entity", "relevant_chunks", ["session_id", "entity_type"], unique=False
    )
    op.create_index(op.f("ix_relevant_chunks_doc_id"), "relevant_chunks", ["doc_id"], unique=False)
    op.create_index(op.f("ix_relevant_chunks_entity_type"), "relevant_chunks", ["entity_type"], unique=False)
    op.create_index(op.f("ix_relevant_chunks_session_id"), "relevant_chunks", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relevant_chunks_session_id"), table_name="relevant_chunks")
    op.drop_index(op.f("ix_relevant_chunks_entity_type"), table_name="relevant_chunks")
    op.drop_index(op.f("ix_relevant_chunks_doc_id"), table_name="relevant_chunks")
    op.drop_index("idx_relevant_chunks_session_entity", table_name="relevant_chunks")
    op.drop_index("idx_relevant_chunks_session_id", table_name="relevant_chunks")
    op.drop_index("idx_relevant_chunks_entity_type", table_name="relevant_chunks")
    op.drop_index("idx_relevant_chunks_doc_id", table_name="relevant_chunks")
    op.drop_table("relevant_chunks")
    op.drop_index(op.f("ix_job_progress_job_id"), table_name="job_progress")
    op.drop_table("job_progress")
    op.drop_index(op.f("ix_session_data_session_id"), table_name="session_data")
    op.drop_index(op.f("ix_session_data_key"), table_name="session_data")
    op.drop_index("idx_session_data_session_id", table_name="session_data")
    op.drop_index("idx_session_data_key", table_name="session_data")
    op.drop_table("session_data")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_session_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index("idx_jobs_type", table_name="jobs")
    op.drop_index("idx_jobs_status_type_created", table_name="jobs")
    op.drop_index("idx_jobs_status", table_name="jobs")
    op.drop_index("idx_jobs_session_id", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_documentation_items_source"), table_name="documentation_items")
    op.drop_index(op.f("ix_documentation_items_session_id"), table_name="documentation_items")
    op.drop_index(op.f("ix_documentation_items_page_id"), table_name="documentation_items")
    op.drop_index(op.f("ix_documentation_items_created_at"), table_name="documentation_items")
    op.drop_index("idx_doc_items_source", table_name="documentation_items")
    op.drop_index("idx_doc_items_session_id", table_name="documentation_items")
    op.drop_index("idx_doc_items_page_id", table_name="documentation_items")
    op.drop_index("idx_doc_items_metadata_gin", table_name="documentation_items", postgresql_using="gin")
    op.drop_index("idx_doc_items_created_at", table_name="documentation_items")
    op.drop_table("documentation_items")
    op.drop_index("idx_sessions_updated_at", table_name="sessions")
    op.drop_index("idx_sessions_created_at", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
